name: Docker image build and push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:  docker login hub.docker.com -u $DOCKER_PASSWORD -p $GITHUB_TOKEN
      - name: Build & Tag
        run:  docker build . -t warriorzz/sz-blog-vaadin:v1.1 -t warriorzz/sz-blog-vaadin:latest .
      - name: Push
        run:  docker push ${{ secrets.DOCKER_USER }}/sz-blog-vaadin:latest
      - name: Push specific tag
        run:  docker push ${{ secrets.DOCKER_USER }}/sz-blog-vaadin:v1.1
